version: '3.0'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  postgres-data: