server:
  port: 8888
  servlet:
    context-path: /api/
spring:
  jpa:
    generate-ddl: true
    hibernate:
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://batyr.db.elephantsql.com:5432/jtcwbayz
    username: jtcwbayz
    password: EwltmzGXY6B78fplwI_HX4ORQOTieN_e
